### ISSUE TITLE
`npm install json2xlxs` not working

### ISSUE THREAD

**Issue by csicar** [digplan/json2xlsx#2]
When trying to install the package from the npm registry I'm getting this error:

``` bash
404 https://registry.npmjs.org/json2xlsx/-/json2xlsx-0.1.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/json2xlsx/-/json2xlsx-0.1.4.tgz
npm ERR! Error: 404 Not Found
```

(local install is working all fine.)

btw awesome package; I'd like to use it in a project, but there is no license. It could help to add that.

**Comment by gaya3k31** [comment]
is it compulsory to clone in github for installing json2xlsx module

**Comment by digplan** [comment]
You should be able to use:  npm install digplan/json2xlsx
