### ISSUE TITLE
npm install命令无法正确安装

### ISSUE THREAD

**Issue by gavinning** [digplan/json2xlsx#6]
![image](https://cloud.githubusercontent.com/assets/1996344/8741654/df895130-2c8e-11e5-83e6-9571162534b6.png)

不知道什么原因，通过npm无法正确安装该模块，报错404，上图是错误信息，初步测试可能是依赖声明有问题，希望可以修复一下这个问题。
因为项目着急使用，我复制了一个副本json2xlsx-copy提交到npm，作为暂时的依赖，已经声明为json2xlsx的副本，并链接指向json2xlsx，请允许，当bug修复后我将会删除这个副本

**Comment by digplan** [comment]
现在固定。谢谢
